name: ci

on: push

jobs:
  test:
    name: test bashert on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15]
    steps:
      - uses: actions/checkout@v2.3.4

      - name: run the example test case on ubuntu
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          source <(curl -sSf https://raw.githubusercontent.com/chiefbiiko/bashert/v1.1.0/bashert.sh)
          source ./test_suite.sh
          test_users_list_200

      - name: run the example test case on macos
        if: startsWith(matrix.os, 'macos')
        run: |
          source ./bashert.sh
          source ./test_suite.sh
          test_users_list_200
          test_assert_files_equal