name: ci

on: push

jobs:
  test:
    name: test bashert on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11.0]
    steps:
      - uses: actions/checkout@v2.3.4

      - name: run the example test case
        run: |
          source <(curl -sSf https://raw.githubusercontent.com/chiefbiiko/bashert/v1.0.1/bashert.sh)
          source ./test_suite.sh
          test_users_list_200